photography_blog/ad_mannager/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('post-create/', views.post_create, name='post-create'),
    path('login/', views.auth_login, name='login'),
    path('logout/', views.logoutControl, name='logout'),
    path('post-edit/<slug:slug>', views.edit_post, name="post-edit"),
    path('profile/<int:id>', views.profile, name="profile"),
    path('post-setting/', views.p_setting, name='post-setting'),
    path('detail-setting/', views.d_setting, name='detail-setting'),
    path('post-detail/<slug:slug>', views.post_detail, name="post-detail"),
    path('remove-confirm/<slug:slug>', views.remove_confirm, name="remove-confirm"),
    path('remove/<slug:slug>', views.remove, name="remove"),
    path('member-list/', views.member_list, name='member-list'),
    path('member-create/', views.signup, name="member-create"),
    
]

photography_blog/photography_blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('habeii/', include('habeii.urls')),
    path('ad_mannager/', include('ad_mannager.urls')),
    path('summernote/', include('django_summernote.urls')),  
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photography_blog/ad_mannager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify
from unidecode import unidecode
# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=25)

    def __str__(self):
        return self.category_name

class Status(models.Model):
    status_name = models.CharField(max_length=25)
    
    def __str__(self):
        return self.status_name

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    thumbnail = models.FileField(upload_to="thumbnail image")
    slug = models.SlugField(null=False, unique=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)
    isDelete = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": self.slug})
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, null=True)
    task = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=255, null=True)
    birthday = models.DateField(null=True)
    avatar = models.ImageField(default='default.png', upload_to='profile_images')
    bio = models.TextField(null=True)

    def __str__(self):
        return self.user.username

photography_blog/ad_mannager/forms.py
from cProfile import label
from dataclasses import field, fields
from django import forms
from .models import Category, Post, Profile, Status
from django_summernote.widgets import SummernoteWidget
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('user', 'title', 'category', 'content', 'thumbnail', 'status', 'tags')
        widgets = {
            'content' : SummernoteWidget(),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            # 'content': forms.Textarea(attrs={'class': 'summernote'}),
            'category': forms.Select(attrs={'class': 'form-control selectric'}),
            'user': forms.Select(attrs={'class': 'form-control selectric'}),
            'status': forms.Select(attrs={'class': 'form-control selectric'}),
            'thumbnail': forms.FileInput(attrs={'id': 'image-upload'}),  
            'tags': forms.TextInput(attrs={'class': 'form-control inputtags'}),
        }
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True
        
        self.fields['user'].label = '記者'
        self.fields['title'].label = 'タイトル'  
        self.fields['category'].label = 'カテゴリー'
        self.fields['content'].label = 'コンテンツ'
        self.fields['status'].label = '状態'
        

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'username' : forms.TextInput(attrs={'class':'form-control'}),
            'password' : forms.PasswordInput(attrs={'class':'form-control'})
        }

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        
    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        self.fields['email'].required = True

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'phone', 'task', 'avatar', 'address', 'birthday']
        widgets = {
            'bio' : SummernoteWidget(),
        }
    
    def __init__(self, *args, **kwargs):
        super(UpdateProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            if field != self.fields['bio']:
                field.widget.attrs["class"] = "form-control"
            field.required = False
            

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='任意。', label='名')
    last_name = forms.CharField(max_length=30, required=False, help_text='任意。', label='苗字')
    email = forms.EmailField(max_length=254, help_text='必要。有効な電子メール アドレスを通知します。', label='メール')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
       
class CreateCategorys(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name']
    def __init__(self, *args, **kwargs):
        super(CreateCategorys, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        self.fields['category_name'].required = True

class CreateStatus(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status_name']
    def __init__(self, *args, **kwargs):
        super(CreateStatus, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        self.fields['status_name'].required = True

photography_blog/ad_mannager/views.py
import os
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from ad_mannager.forms import CreateCategorys, LoginForm, PostForm, SignUpForm, UpdateProfileForm, UpdateUserForm
from .models import Category, Post, Status
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import get_user_model

# Create your views here.

@login_required()
def index(request):
    posts = Post.objects.order_by('-id')
    len_all = 0
    len_public_post = 0
    len_pending_post = 0
    len_draft_post = 0
    len_removed_post = 0
    
    len_all = len(posts)
    
    for post in posts:
        if post.isDelete == True:
            len_removed_post += 1
        
        if post.status.status_name == "公衆":
            len_public_post += 1
        elif post.status.status_name == "保留中":
            len_pending_post += 1
        elif post.status.status_name == "下書き":
            len_draft_post += 1
   
    context = {
        'posts': posts,
        'len_all' : len_all,
        'len_public_post' : len_public_post,
        'len_pending_post' : len_pending_post,
        'len_draft_post' : len_draft_post,
        'len_removed_post' : len_removed_post
    }
    
    return render(request, 'ad_mannager/posts.html', context)

@login_required()
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('post:index')
        else:
            return render(request, 'ad_mannager/post-create.html', {'form':form})
    else:
        form = PostForm()
        return render(request, 'ad_mannager/post-create.html', {'form':form})

def auth_login(request):
    lf = LoginForm
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        next_url = request.POST['next']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect(next_url)
            ...
        else:
            request_form = LoginForm(request.POST)
            # Return an 'invalid login' error message.
            mess="パスワードまたはアカウント名が間違っているので、再試行してください。"
            ...
            return render(request, 'ad_mannager/login.html', {'mess':mess, 'form':request_form, 'next':next_url})

            
    else:
        return render(request, 'ad_mannager/login.html', {'form':lf})

@login_required()
def logoutControl(request):
    logout(request)
    return redirect('post:login')


@login_required()
def edit_post(request, slug):
    post = get_object_or_404(Post, slug = slug)
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            if post.isDelete == True and form['status'] != "消去済":
                post.isDelete = False
            form.save()
            return redirect('post:index')
        else:
            return render(request, 'ad_mannager/post-edit.html', {'form':form, 'post' : post})
    else:
        tags = post.tags.all()
        form = PostForm(instance=post)
        return render(request, 'ad_mannager/post-edit.html', {'form':form, 'post': post, 'tags':tags})

@login_required()
def profile(request, id):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=user)
        profile_form = UpdateProfileForm(request.POST, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            path_old_img = (user.profile.avatar.url).lstrip("/")
            
            new_avatar = request.FILES.get('avatar', None)
            user_form.save()
            profile_form.save()
            
            if new_avatar != None and path_old_img != 'media/default.png':
                try:
                    os.remove(path_old_img)
                except Exception as e:
                    print('Exception in removing old profile image: ', e)
                user.profile.avatar = request.FILES.get('avatar', None)
                user.profile.save()
            elif new_avatar != None:
                user.profile.avatar = request.FILES.get('avatar', None)
                user.profile.save()
                
            messages.success(request, 'Your profile is updated successfully')
            return redirect('post:profile', id=user.id)
    else:
      
        user_form = UpdateUserForm(instance=user)
        profile_form = UpdateProfileForm(instance=user.profile)

    return render(request, 'ad_mannager/profile.html', {'user_form': user_form, 'profile_form': profile_form, 'uf':user})

@login_required()
def p_setting(request):
    category_all = Category.objects.all()
    if request.method == 'POST':
       create_categoryForm = CreateCategorys(request.POST)
       if create_categoryForm.is_valid():
           create_categoryForm.save()
           return redirect('post:post-setting')
    else:
        create_categoryForm = CreateCategorys()
    return render(request, 'ad_mannager/post-setting.html', {'create_categoryForm':create_categoryForm, 'category_all':category_all})
        
    
@login_required()
def d_setting(request):
    if request.method == 'GET':
        return render(request, 'ad_mannager/detail-setting.html')

@login_required()  
def post_detail(request, slug):
    post = get_object_or_404(Post, slug = slug)
    return render(request, 'ad_mannager/review.html', {'post':post})

@login_required()
def remove_confirm(request, slug): 
    return render(request, 'ad_mannager/remove-confirm.html', {'slug':slug})

@login_required()
def remove(request, slug):
    post = get_object_or_404(Post, slug = slug)
    post.isDelete = True
    stus = get_object_or_404(Status, id=5)
    post.status = stus
    post.save()
    return redirect('post:index')

@login_required()
def member_list(request):
    User = get_user_model()
    member_list = User.objects.all()
    len_members = len(member_list)

    context = {
        'member_list' : member_list,
        'len_members' : len_members,
    }
    return render(request, 'ad_mannager/member-list.html', context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('post:member-list')
    else:
        form = SignUpForm()
    return render(request, 'ad_mannager/member-create.html', {'form':form})

photography_blog/ad_mannager/templates/ad_mannager/base.html
<!DOCTYPE html>

<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <link rel="icon" type="image/x-icon" href="/media/favicon.ico">
  <title> Habeii &rsaquo; {% block title %}{% endblock title %}</title>
 
 
  <!-- General CSS Files -->
  <link rel="stylesheet" href=" {% static 'ad_mannager/assets/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/modules/summernote/summernote-bs4.css' %}">
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/modules/codemirror/lib/codemirror.css' %}">
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/modules/codemirror/theme/duotone-dark.css' %}">
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/modules/jquery-selectric/selectric.css' %}">
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'ad_mannager/assets/css/components.css' %}">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
<!-- /END GA --></head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
          </ul>
        </form>
        <ul class="navbar-nav navbar-right">   
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{{user.profile.avatar.url}}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">こんにちは、 {{user.first_name}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-title">5分前に訪問しました</div>
              <a href="{% url 'post:profile' user.id %}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> 個人ページ
              </a>
              <a href="features-settings.html" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> 設定
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'post:logout' %}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> ログアウト
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar sidebar-style-2">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{% url 'post:index' %}"><img src="{% static 'ad_mannager/assets/img/logo.png' %}" alt="">Habeii</a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="{% url 'post:index' %}"><img src="{% static 'ad_mannager/assets/img/logo.png' %}" alt=""></a>
          </div>
          <ul class="sidebar-menu">
            <li class="menu-header">ページ</li>
            <li class="dropdown active">
              <a href="#" class="nav-link has-dropdown"><i class="fas fa-bicycle"></i> <span>ページ管理</span></a>
              <ul class="dropdown-menu">  
                <li {% block active_index %}{% endblock active_index %}><a class="nav-link" href="{% url 'post:index' %}">投稿一覧</a></li>
                <li {% block active_create %}{% endblock active_create %}><a class="nav-link" href="{% url 'post:post-create' %}">投稿を作成する</a></li>
                <li {% block active_profile %}{% endblock active_profile %}><a class="nav-link" href="{% url 'post:profile' user.id%}">個人ページ</a></li>
                <li {% block active_member_list %}{% endblock active_member_list %}><a class="nav-link" href="{% url 'post:member-list'%}">メンバー管理</a></li>
                <li {% block active_setting_post %}{% endblock active_setting_post %}><a class="nav-link" href="{% url 'post:post-setting' %}">ブログについて設定</a></li>
                <li {% block active_setting_detail %}{% endblock active_setting_detail %}><a class="nav-link" href="{% url 'post:detail-setting' %}">詳細設定</a></li>
              </ul>
            </li>
          </ul>
        </aside>
      </div>

{% block content %}{% endblock content %}


    <footer class="main-footer">
        <div class="footer-left">
        Copyright &copy; 2022 <div class="bullet"></div> Design By ファムタインハウ
        </div>
        <div class="footer-right">
        
        </div>
    </footer>
    </div>
    </div>
        
  <!-- General JS Scripts -->
  <script src="{% static 'ad_mannager/assets/modules/jquery.min.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/popper.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/tooltip.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/moment.min.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/js/stisla.js' %}"></script>
  
  <!-- JS Libraies -->
  <script src="{% static 'ad_mannager/assets/modules/summernote/summernote-bs4.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/jquery-selectric/jquery.selectric.min.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static 'ad_mannager/assets/js/page/features-posts.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/js/page/features-post-create.js' %}"></script>
  
  <!-- Template JS File -->
  <script src="{% static 'ad_mannager/assets/js/scripts.js' %}"></script>
  <script src="{% static 'ad_mannager/assets/js/custom.js' %}"></script>
</body>
</html>

photography_blog/ad_mannager/templates/ad_mannager/posts.html
<!DOCTYPE html>
{% extends 'ad_mannager/base.html' %}

{% block title %}ホームページ{% endblock title %}

{% block active_index %}class="active"{% endblock active_index %}

{% block content %}
{% load static %}
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>投稿一覧</h1>
            <div class="section-header-button">
              <a href="{% url 'post:post-create' %}" class="btn btn-primary">新しい投稿を追加</a>
            </div>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href=".">Habeii</a></div>
              <div class="breadcrumb-item"><a href=".">投稿</a></div>
              <div class="breadcrumb-item">すべての投稿</div>
            </div>
          </div>
          <div class="section-body">
            <h2 class="section-title">投稿</h2>
            <p class="section-lead">
              編集、削除など、すべての投稿を管理できます。
            </p>

            <div class="row">
              <div class="col-12">
                <div class="card mb-0">
                  <div id="myDIV" class="card-body">
                    <ul class="nav nav-pills">
                      <li class="nav-item">
                        <button class="btn active" onclick="findBy('全て')">全て<span class="badge badge-white">{{len_all}}</span></button>
                      </li>
                      <li class="nav-item">
                        <button class="btn" onclick="findBy('公衆')">公衆<span class="badge badge-white">{{len_public_post}}</span></button>
                      </li>
                      <li class="nav-item">
                        <button class="btn" onclick="findBy('下書き')">下書き<span class="badge badge-white">{{len_draft_post}}</span></button>
                      </li>
                      <li class="nav-item">
                        <button class="btn" onclick="findBy('保留中')">保留中<span class="badge badge-white">{{len_pending_post}}</span></button>
                      </li>
                      <li class="nav-item">
                        <button class="btn" onclick="findBy('消去済')">ゴミ箱<span class="badge badge-white">{{len_removed_post}}</span></button>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col-12">
                <div class="card">
                  
                  <div class="card-body">
                    <div class="float-right">                    
                        <div class="input-group">
                          <input type="text" id="myInput" onkeyup="myFunction()" class="form-control" placeholder="タイトルで検索">
                          <div class="input-group-append">                                            
                            <i class="fas fa-search btn btn-primary"></i>
                          </div>
                        </div>
                    </div>

                    <div class="clearfix mb-3"></div>

                    <div class="table-responsive">
                      <table id="myTable" class="table table-striped">
                        <tr>
                          <th>タイトル</th>
                          <th>カテゴリー</th>
                          <th>著者</th>
                          <th>作成日</th>
                          <th>状態</th>
                        </tr>
                        {% for post in posts %}
                          <tr>
                            <td>{{post.title}}
                              
                              <div class="table-links">
                                {% if post.status.id != 5 %}
                                <a href="{% url 'post:post-detail' post.slug %}">見る</a>
                                <div class="bullet"></div>
                                <a href="{% url 'post:post-edit' post.slug %}">編集</a>
                                <div class="bullet"></div>
                                <a href="{% url 'post:remove-confirm' post.slug %}" class="text-danger">消去</a>
                                {% else %}
                                <a href="{% url 'post:post-edit' post.slug %}" class="text-danger">復活</a>
                                {% endif %}
                                
                              </div>
                              
                            </td>
                            <td>
                              {{post.category}}
                            </td>
                            <td>
                              <a href="{% url 'post:profile' post.user_id %}">
                                <img alt="image" src="{{post.user.profile.avatar.url}}" class="rounded-circle" width="35" data-toggle="title" title=""> <div class="d-inline-block ml-1">{{post.user.last_name}}</div>
                              </a>
                            </td>
                            <td>{{post.create_at}}</td>
                            {% if post.status.status_name == "公衆" %}
                            <td><div class="badge badge-success">{{post.status}}</div></td>
                            {% elif post.status.status_name == "下書き" %}
                            <td><div class="badge badge-warning">{{post.status}}</div></td>
                            {% elif post.status.status_name == "保留中" %}
                            <td><div class="badge badge-danger">{{post.status}}</div></td>
                            {% else %}
                            <td><div class="badge badge-secondary">{{post.status}}</div></td>
                            {% endif %}
                      
                          </tr>
                        {% endfor %}
                      </table>
                    </div>

                    <div class="float-right">
                      <nav>
                        <ul class="pagination">
                          <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                              <span aria-hidden="true">&laquo;</span>
                              <span class="sr-only">Previous</span>
                            </a>
                          </li>
                          <li class="page-item active">
                            <a class="page-link" href="#">1</a>
                          </li>
                          <li class="page-item">
                            <a class="page-link" href="#">2</a>
                          </li>
                          <li class="page-item">
                            <a class="page-link" href="#">3</a>
                          </li>
                          <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">次</span>
                            </a>
                          </li>
                        </ul>
                      </nav>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      
      <script>
        function myFunction() {
          // Declare variables
          var input, filter, table, tr, td, i, txtValue;
          input = document.getElementById("myInput");
          filter = input.value.toUpperCase();
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");
        
          // Loop through all table rows, and hide those who don't match the search query
          for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
              txtValue = td.textContent || td.innerText;
              if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
              } else {
                tr[i].style.display = "none";
              }
            }
          }
        }

        function findBy(text){
          // Declare variables
          var input, filter, table, tr, td, i, txtValue;
          if(text == '全て'){
            text = ''
          }
          input = text
          filter = input.toUpperCase();
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");
        
          // Loop through all table rows, and hide those who don't match the search query
          for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[4];
            if (td) {
              txtValue = td.textContent || td.innerText;
              if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
              } else {
                tr[i].style.display = "none";
              }
            }
          }
        }
        </script>
        <script>
          // Add active class to the current button (highlight it)
          var header = document.getElementById("myDIV");
          var btns = header.getElementsByClassName("btn");
          for (var i = 0; i < btns.length; i++) {
            btns[i].addEventListener("click", function() {
            var current = document.getElementsByClassName("active");
            current[0].className = current[0].className.replace(" active", "");
            this.className += " active";
            });
          }
          </script>
  {% endblock content %}